export default {
  SEARCH_VALUE_CHANGE: 'SEARCH_VALUE_CHANGE',
  SEARCH_API_START: 'SEARCH_API_START',
  SEARCH_API_SUCCESS: 'SEARCH_API_SUCCESS',
  SEARCH_API_ERROR: 'SEARCH_API_ERROR',
  SELECT_TOPIC: 'SELECT_TOPIC',
  SET_LAST_DROPPED_ITEM: 'SET_LAST_DROPPED_ITEM',
  TOGGLE_OVERLAY_VISIBILITY: 'TOGGLE_OVERLAY_VISIBILITY',
};
