export default {
  SEARCH_API_START: 'SEARCH_API_START',
  SEARCH_API_SUCCESS: 'SEARCH_API_SUCCESS',
  SEARCH_API_ERROR: 'SEARCH_API_ERROR',
  SELECT_TOPIC: 'SELECT_TOPIC',
  SHARE_TOPIC: 'SHARE_TOPIC',
  SET_SHARE_TOPIC: 'SET_SHARE_TOPIC',
  TOGGLE_OVERLAY_VISIBILITY: 'TOGGLE_OVERLAY_VISIBILITY',
};
